version: 0.2
phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  pre_build:
    commands:
      - ls
      - cp $CODEBUILD_SRC_DIR_Infra/config/env.txt $CODEBUILD_SRC_DIR_App/.env 
      - cp $CODEBUILD_SRC_DIR_Infra/Docker/Dockerfile $CODEBUILD_SRC_DIR_App
      - cp $CODEBUILD_SRC_DIR_Infra/config/app_nginx.conf $CODEBUILD_SRC_DIR_App
      - cp $CODE_BUILD_SRC_DIR_Infra/config/nginx.conf $CODEBUILD_SRC_DIR_App
      - cp $CODE_BUILD_SRC_DIR_Infra/scripts/entrypoint.sh $CODEBUILD_SRC_DIR_App
      - cd $CODEBUILD_SRC_DIR_App
      - ls
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s:%s"}' "$REPOSITORY_URI" "$TAG" > /tmp/build.json
artifacts:
  files: 
    - /tmp/build.json
  discard-paths: yes