version: 0.2
env:
  parameter-store:
    DB_USERNAME: "/ECS-CLUSTER/${CLUSTER_NAME}/RDS_ROOT_USERNAME"
    DB_PASSWORD: "/ECS-CLUSTER/${CLUSTER_NAME}/RDS_ROOT_PASSWORD"
    DB_HOST: "/ECS-CLUSTER/${CLUSTER_NAME}/RDS_ADDRESS"
    DB_PORT: "/ECS-CLUSTER/${CLUSTER_NAME}/RDS_PORT"

  secrets-manager:
    APP_NAME: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:APP_NAME "
    APP_ENV: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:APP_ENV"
    APP_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:APP_KEY"
    APP_DEBUG: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:APP_DEBUG"
    APP_URL: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:APP_URL"
    LOG_CHANNEL: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:LOG_CHANNEL"
    LOG_LEVEL: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:LOG_LEVEL"
    DB_CONNECTION: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:DB_CONNECTION"
    DB_DATABASE: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:DB_DATABASE"
    BROADCAST_DRIVER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:BROADCAST_DRIVER"
    CACHE_DRIVER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:CACHE_DRIVER"
    FILESYSTEM_DRIVER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:FILESYSTEM_DRIVER"
    QUEUE_CONNECTION: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:QUEUE_CONNECTION"
    SESSION_DRIVER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:SESSION_DRIVER"
    SESSION_LIFETIME: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:SESSION_LIFETIME"
    MEMCACHED_HOST: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MEMCACHED_HOST"
    REDIS_HOST: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:REDIS_HOST"
    REDIS_PASSWORD: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:REDIS_PASSWORD"
    REDIS_PORT: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:REDIS_PORT"
    MAIL_MAILER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_MAILER"
    MAIL_HOST: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_HOST"
    MAIL_PORT: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_PORT"
    MAIL_USERNAME: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_USERNAME"
    MAIL_PASSWORD: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_PASSWORD"
    MAIL_ENCRYPTION: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_ENCRYPTION"
    MAIL_FROM_ADDRESS: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_FROM_ADDRESS"
    MAIL_FROM_NAME: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MAIL_FROM_NAME"
    AWS_ACCESS_KEY_ID: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:AWS_ACCESS_KEY_ID"    
    AWS_SECRET_ACCESS_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:AWS_SECRET_ACCESS_KEY"    
    AWS_DEFAULT_REGION: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:AWS_DEFAULT_REGION"
    AWS_BUCKET: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:AWS_BUCKET"
    AWS_USE_PATH_STYLE_ENDPOINT: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:AWS_USE_PATH_STYLE_ENDPOINT"
    PUSHER_APP_ID: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:PUSHER_APP_ID"    
    PUSHER_APP_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:PUSHER_APP_KEY"
    PUSHER_APP_SECRET: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:PUSHER_APP_SECRET"    
    PUSHER_APP_CLUSTER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:PUSHER_APP_CLUSTER"
    MIX_PUSHER_APP_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MIX_PUSHER_APP_KEY"
    MIX_PUSHER_APP_CLUSTER: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MIX_PUSHER_APP_CLUSTER"
    STREAM_API_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STREAM_API_KEY"
    STREAM_API_SECRET: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STREAM_API_SECRET"
    MIX_STREAM_API_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MIX_STREAM_API_KEY"
    MIX_STREAM_API_SECRET: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:MIX_STREAM_API_SECRET"
    STRIPE_KEY_live: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STRIPE_KEY_live"
    STRIPE_SECRET_live: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STRIPE_SECRET_live"
    STRIPE_KEY: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STRIPE_KEY"
    STRIPE_SECRET: "${CLUSTER_NAME}/${PROJECT_NAME}/${ENVIRONMENT}:STRIPE_SECRET"

phases:
  install:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  pre_build:
    commands:      
      - sh scripts/sed-env.sh
      - cp config/env.txt $CODEBUILD_SRC_DIR_App/.env
      - cp Docker/Dockerfile $CODEBUILD_SRC_DIR_App
      - cp config/app_nginx.conf $CODEBUILD_SRC_DIR_App
      - cp config/nginx.conf $CODEBUILD_SRC_DIR_App
      - cp scripts/entrypoint.sh $CODEBUILD_SRC_DIR_App
      - cd $CODEBUILD_SRC_DIR_App  
      - cat .env
      - docker build --tag "${REPOSITORY_URI}:${TAG}" .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:${TAG}"
      - printf '{"tag":"%s:%s"}' "$REPOSITORY_URI" "$TAG" > /tmp/build.json
artifacts:
  files: 
    - /tmp/build.json
  discard-paths: yes