#!/bin/bash
sed -i "s|ENV_APP_ENV|${APP_ENV}|g" config/env.txt
sed -i "s|ENV_APP_NAME|${APP_NAME}|g" config/env.txt
sed -i "s|ENV_APP_KEY|${APP_KEY}|g" config/env.txt
sed -i "s|ENV_APP_DEBUG|${APP_DEBUG}|g" config/env.txt
sed -i "s|ENV_APP_URL|${APP_URL}|g" config/env.txt
sed -i "s|ENV_LOG_CHANNEL|${LOG_CHANNEL}|g" config/env.txt
sed -i "s|ENV_LOG_LEVEL|${LOG_LEVEL}|g" config/env.txt
sed -i "s|ENV_DB_CONNECTION|${DB_CONNECTION}|g" config/env.txt
sed -i "s|ENV_DB_HOST|${DB_HOST}|g" config/env.txt
sed -i "s|ENV_DB_PORT|${DB_PORT}|g" config/env.txt
sed -i "s|ENV_DB_DATABASE|${DB_DATABASE}|g" config/env.txt
sed -i "s|ENV_DB_USERNAME|${DB_USERNAME}|g" config/env.txt
sed -i "s|ENV_DB_PASSWORD|${DB_PASSWORD}|g" config/env.txt
sed -i "s|ENV_BROADCAST_DRIVER|${BROADCAST_DRIVER}|g" config/env.txt
sed -i "s|ENV_CACHE_DRIVER|${CACHE_DRIVER}|g" config/env.txt
sed -i "s|ENV_FILESYSTEM_DRIVER|${FILESYSTEM_DRIVER}|g" config/env.txt
sed -i "s|ENV_QUEUE_CONNECTION|${QUEUE_CONNECTION}|g" config/env.txt
sed -i "s|ENV_SESSION_DRIVER|${SESSION_DRIVER}|g" config/env.txt
sed -i "s|ENV_SESSION_LIFETIME|${SESSION_LIFETIME}|g" config/env.txt
sed -i "s|ENV_MEMCACHED_HOST|${MEMCACHED_HOST}|g" config/env.txt
sed -i "s|ENV_REDIS_HOST|${REDIS_HOST}|g" config/env.txt
sed -i "s|ENV_REDIS_PASSWORD|${REDIS_PASSWORD}|g" config/env.txt
sed -i "s|ENV_REDIS_PORT|${REDIS_PORT}|g" config/env.txt
sed -i "s|ENV_MAIL_MAILER|${MAIL_MAILER}|g" config/env.txt
sed -i "s|ENV_MAIL_HOST|${MAIL_HOST}|g" config/env.txt
sed -i "s|ENV_MAIL_PORT|${MAIL_PORT}|g" config/env.txt
sed -i "s|ENV_MAIL_USERNAME|${MAIL_USERNAME}|g" config/env.txt
sed -i "s|ENV_MAIL_PASSWORD|${MAIL_PASSWORD}|g" config/env.txt
sed -i "s|ENV_MAIL_ENCRYPTION|${MAIL_ENCRYPTION}|g" config/env.txt
sed -i "s|ENV_MAIL_FROM_ADDRESS|${MAIL_FROM_ADDRESS}|g" config/env.txt
sed -i "s|ENV_MAIL_FROM_NAME|${MAIL_FROM_NAME}|g" config/env.txt
sed -i "s|ENV_AWS_ACCESS_KEY_ID|${AWS_ACCESS_KEY_ID}|g" config/env.txt
sed -i "s|ENV_AWS_SECRET_ACCESS_KEY|${AWS_SECRET_ACCESS_KEY}|g" config/env.txt
sed -i "s|ENV_AWS_DEFAULT_REGION|${AWS_DEFAULT_REGION}|g" config/env.txt
sed -i "s|ENV_AWS_BUCKET|${AWS_BUCKET}|g" config/env.txt
sed -i "s|ENV_AWS_USE_PATH_STYLE_ENDPOINT|${AWS_USE_PATH_STYLE_ENDPOINT}|g" config/env.txt
sed -i "s|ENV_PUSHER_APP_ID|${PUSHER_APP_ID}|g" config/env.txt
sed -i "s|ENV_PUSHER_APP_KEY|${PUSHER_APP_KEY}|g" config/env.txt
sed -i "s|ENV_PUSHER_APP_SECRET|${PUSHER_APP_SECRET}|g" config/env.txt
sed -i "s|ENV_PUSHER_APP_CLUSTER|${PUSHER_APP_CLUSTER}|g" config/env.txt
sed -i "s|ENV_MIX_PUSHER_APP_KEY|${MIX_PUSHER_APP_KEY}|g" config/env.txt
sed -i "s|ENV_MIX_PUSHER_APP_CLUSTER|${MIX_PUSHER_APP_CLUSTER}|g" config/env.txt
sed -i "s|ENV_STREAM_API_KEY|${STREAM_API_KEY}|g" config/env.txt
sed -i "s|ENV_STREAM_API_SECRET|${STREAM_API_SECRET}|g" config/env.txt
sed -i "s|ENV_MIX_STREAM_API_KEY|${MIX_STREAM_API_KEY}|g" config/env.txt
sed -i "s|ENV_MIX_STREAM_API_SECRET|${MIX_STREAM_API_SECRET}|g" config/env.txt
sed -i "s|ENV_STRIPE_KEY_live|${STRIPE_KEY_live}|g" config/env.txt
sed -i "s|ENV_STRIPE_SECRET_live|${STRIPE_SECRET_live}|g" config/env.txt
sed -i "s|ENV_STRIPE_KEY|${STRIPE_KEY}|g" config/env.txt
sed -i "s|ENV_STRIPE_SECRET|${STRIPE_SECRET}|g" config/env.txt